//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bloodbankEntities9 : DbContext
    {
        public bloodbankEntities9()
            : base("name=bloodbankEntities9")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bloodrequest> bloodrequests { get; set; }
        public virtual DbSet<donation> donations { get; set; }
        public virtual DbSet<experience> experiences { get; set; }
        public virtual DbSet<like> likes { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
