//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bloodrequest
    {
        public bloodrequest()
        {
            this.donations = new HashSet<donation>();
        }
    
        public int bloodrequestid { get; set; }
        public int userid { get; set; }
        public string bloodgroup { get; set; }
        public System.DateTime datetime { get; set; }
        public string presentlocation { get; set; }
        public bool ishandle { get; set; }
    
        public virtual user user { get; set; }
        public virtual ICollection<donation> donations { get; set; }
    }
}
