//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class like
    {
        public int likeid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> expid { get; set; }
    
        public virtual experience experience { get; set; }
        public virtual user user { get; set; }
    }
}
