//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.bloodrequests = new HashSet<bloodrequest>();
            this.donations = new HashSet<donation>();
            this.experiences = new HashSet<experience>();
            this.likes = new HashSet<like>();
        }
    
        public int Id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string gender { get; set; }
        public string city { get; set; }
        public string bloodgroup { get; set; }
        public string phoneNo { get; set; }
        public bool agreed { get; set; }
    
        public virtual ICollection<bloodrequest> bloodrequests { get; set; }
        public virtual ICollection<donation> donations { get; set; }
        public virtual ICollection<experience> experiences { get; set; }
        public virtual ICollection<like> likes { get; set; }
    }
}
